### ISSUE TITLE
[Broken Plugin] Update for the latest WHMCS with PHP 8 Support

### ISSUE THREAD

**Issue by upal212** [2Checkout/whmcs#4]
Kindly update the plugin to support PHP 8 as PHP 7.4 is depreciated and your plugin is now broken and does not work which generates handling errors.

**Comment by insave-hosting** [comment]
Yes, please fix it.

**Comment by deendoughouz** [comment]
Hi,

I am getting empty card issue when paying an invoice, but when I click on mass invoice pay it works now. Any help or fix for this issue?

Bests

**Comment by azizarnold** [comment]
getting same issue on php 8.1 with latest whmcs release.

Once I upload this plugin immediately the whole payment gateway page is broke and cannot see or configure any plugins.

error returned :

Error: Non-static method TwocheckoutHelper::config() cannot be called statically in ../modules/gateways/twocheckoutapi.php:199]
Stack trace:
#0 [internal function]: twocheckoutapi_config()

Have to delete all the files uploaded for whmcs to function again and us to access the payment gateway page.

**Comment by craigchristenson** [comment]
I am sorry for the delay in getting this addressed. We have now fixed this issue in the latest release.
